/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package temperatureconverter;

/**
 *
 * @author Adarsh Mishra
 */
public class TempConv extends javax.swing.JFrame {

    /**
     * Creates new form TempConv
     */
    public TempConv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttemp = new javax.swing.JTextField();
        btnctof = new javax.swing.JButton();
        btnftoc = new javax.swing.JButton();
        btnclr = new javax.swing.JButton();
        lblres = new javax.swing.JLabel();
        btnctok = new javax.swing.JButton();
        btnktoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Temperature Converter");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Enter Temperature");

        txttemp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttempActionPerformed(evt);
            }
        });

        btnctof.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnctof.setForeground(new java.awt.Color(0, 0, 255));
        btnctof.setText("CToF");
        btnctof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnctofActionPerformed(evt);
            }
        });

        btnftoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnftoc.setForeground(new java.awt.Color(51, 51, 255));
        btnftoc.setText("FToC");
        btnftoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnftocActionPerformed(evt);
            }
        });

        btnclr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclr.setForeground(new java.awt.Color(255, 0, 0));
        btnclr.setText("CLEAR");
        btnclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclrActionPerformed(evt);
            }
        });

        lblres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblres.setForeground(new java.awt.Color(0, 0, 255));
        lblres.setText("Result");

        btnctok.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnctok.setForeground(new java.awt.Color(0, 0, 255));
        btnctok.setText("CToK");
        btnctok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnctokActionPerformed(evt);
            }
        });

        btnktoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnktoc.setForeground(new java.awt.Color(51, 0, 255));
        btnktoc.setText("KToC");
        btnktoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnktocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addComponent(txttemp, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnctof)
                        .addGap(39, 39, 39)
                        .addComponent(btnftoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnctok)
                        .addGap(46, 46, 46)
                        .addComponent(btnktoc)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclr)
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnctof)
                            .addComponent(btnftoc)
                            .addComponent(btnctok)
                            .addComponent(btnktoc))
                        .addGap(65, 65, 65)
                        .addComponent(lblres))
                    .addComponent(btnclr))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttempActionPerformed
        
    }//GEN-LAST:event_txttempActionPerformed

    private void btnctofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnctofActionPerformed
        double c,f;
        c=Double.parseDouble(txttemp.getText());
        f=(9*c)/5+32;
        lblres.setText("Temperature in f : "+f);
    }//GEN-LAST:event_btnctofActionPerformed

    private void btnftocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnftocActionPerformed
        // TODO add your handling code here:
               double c,f;
       f=Double.parseDouble(txttemp.getText());
       c=(f-32)*5/9;
       lblres.setText("Temperature in c : "+c);
    }//GEN-LAST:event_btnftocActionPerformed

    private void btnctokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnctokActionPerformed
        double c,k;
        c=Double.parseDouble(txttemp.getText());
        k=c+273.15;
        lblres.setText("Temperature in K : "+k);
    }//GEN-LAST:event_btnctokActionPerformed

    private void btnclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclrActionPerformed
        lblres.setText("Result");
        txttemp.setText(" ");
    }//GEN-LAST:event_btnclrActionPerformed

    private void btnktocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnktocActionPerformed
        double c,k;
        k=Double.parseDouble(txttemp.getText());
        c=k-273.15;
        lblres.setText("Temperature in C : "+c);
    }//GEN-LAST:event_btnktocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclr;
    private javax.swing.JButton btnctof;
    private javax.swing.JButton btnctok;
    private javax.swing.JButton btnftoc;
    private javax.swing.JButton btnktoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblres;
    private javax.swing.JTextField txttemp;
    // End of variables declaration//GEN-END:variables
}
